"""
Audit EP5 callback highlights for front-end verification.

For every focal track, this script:
  1. Computes the callback-target set (mirror of findCallbackTargets in TS).
  2. For each target, scans the focal's transcript_zh and transcript_en for
     ANY alias from the EP5 alias table (or the auto-derived artist/song).
  3. Reports each (focal, target) pair as either:
       FIRES — at least one alias is found in some narration paragraph
       SILENT — target is in the candidate set but no alias appears anywhere

Output is a markdown verification table written to `docs/ep5_callback_test.md`.
The user runs the dev server, plays each track, and confirms each row in the
"FIRES" rows actually highlights in the subtitle + lights an arc.
"""
import json
import re
from pathlib import Path

EP5_PATH = Path("musicos-exhibition/data/exhibition-ep5.json")
ALIASES_PATH = Path("musicos-exhibition/src/data/ep5-aliases.ts")
OUT_PATH = Path("docs/ep5_callback_test.md")


def parse_aliases_ts() -> dict[int, list[str]]:
    """Crude TS parser — read the EP5_ALIASES object literal."""
    txt = ALIASES_PATH.read_text()
    out: dict[int, list[str]] = {}
    body = re.search(r"EP5_ALIASES[^=]*=\s*\{([\s\S]*?)\n\};", txt)
    if not body:
        raise SystemExit("Cannot parse EP5_ALIASES")
    for entry in re.finditer(r"^\s*(\d+)\s*:\s*\[([\s\S]*?)\],?\s*(?://.*)?$", body.group(1), re.M):
        pos = int(entry.group(1))
        # Match either a single-quoted or double-quoted string. Group 1 is the
        # double-quoted body, group 2 is the single-quoted body. This avoids
        # splitting on apostrophes inside double-quoted strings like
        # "Japan's Steely Dan" or "It's Too Late".
        items = []
        for m in re.finditer(r'"([^"]*)"|\'([^\']*)\'', entry.group(2)):
            items.append(m.group(1) if m.group(1) is not None else m.group(2))
        out[pos] = items
    return out


def parse_conn(cid: str | None) -> tuple[int, int] | None:
    if not cid:
        return None
    m = re.match(r"^conn_(\d+)_to_(\d+)", cid)
    return (int(m.group(1)), int(m.group(2))) if m else None


def callback_targets(tracks: list[dict], focal_pos: int) -> list[int]:
    ids: set[str] = set()
    for t in tracks:
        if t.get("strong_connection_id"):
            ids.add(t["strong_connection_id"])
        if t.get("position") == focal_pos:
            for a in t.get("archived_weak_connections") or []:
                if a.get("connection_id"):
                    ids.add(a["connection_id"])
    out: set[int] = set()
    for cid in ids:
        p = parse_conn(cid)
        if not p:
            continue
        f, to = p
        if to != focal_pos or f == focal_pos or f <= 0:
            continue
        out.add(f)
    return sorted(out)


def aliases_for(pos: int, track: dict, curated: dict[int, list[str]]) -> list[str]:
    out = list(curated.get(pos, []))
    if track.get("song"):
        out.append(track["song"])
    if track.get("artist"):
        out.append(track["artist"])
    # Dedupe preserving order; sort by length desc so longer wins (matcher does this internally).
    seen = set()
    unique = []
    for a in out:
        if a not in seen:
            seen.add(a)
            unique.append(a)
    unique.sort(key=lambda a: -len(a))
    return unique


def find_first_hit(text: str, aliases: list[str]) -> tuple[str, str] | None:
    """Return (alias, snippet) of the first hit, or None."""
    if not text:
        return None
    best = None
    for a in aliases:
        idx = text.find(a)
        if idx == -1:
            continue
        if best is None or idx < best[2] or (idx == best[2] and len(a) > len(best[0])):
            start = max(0, idx - 25)
            end = min(len(text), idx + len(a) + 25)
            snippet = text[start:end].replace("\n", " ").strip()
            best = (a, snippet, idx)
    if best:
        return best[0], best[1]
    return None


def main() -> None:
    raw = json.loads(EP5_PATH.read_text())
    tracks = [x for x in raw if x.get("kind") == "track"]
    by_pos = {t["position"]: t for t in tracks}
    aliases_map = parse_aliases_ts()

    lines: list[str] = []
    lines.append("# EP5 Callback Highlight Verification Table\n")
    lines.append(
        "Generated by `tools/ep5_callback_audit.py`. For every focal track, every "
        "callback target wired into the candidate set is checked against both ZH "
        "and EN transcripts. **FIRES** rows should produce a transcript pill + arc "
        "in the front-end. **SILENT** rows mean the candidate is wired but the "
        "narration never names it — either the arc needs to be removed or the "
        "narration needs editing.\n",
    )
    lines.append(
        "| Focal pos | Focal track | Target pos | Target track | ZH highlight | EN highlight | Status |"
    )
    lines.append("|---|---|---|---|---|---|---|")

    summary = {"fires_both": 0, "fires_zh_only": 0, "fires_en_only": 0, "silent": 0}

    for t in tracks:
        focal_pos = t["position"]
        targets = callback_targets(tracks, focal_pos)
        if not targets:
            continue
        for tp in targets:
            target = by_pos[tp]
            aliases = aliases_for(tp, target, aliases_map)
            zh_hit = find_first_hit(t.get("transcript_zh") or "", aliases)
            en_hit = find_first_hit(t.get("transcript_en") or "", aliases)
            zh_cell = (
                f"`{zh_hit[0]}` — {zh_hit[1][:70]}…" if zh_hit else "—"
            )
            en_cell = (
                f"`{en_hit[0]}` — {en_hit[1][:70]}…" if en_hit else "—"
            )
            if zh_hit and en_hit:
                status = "FIRES (both)"
                summary["fires_both"] += 1
            elif zh_hit:
                status = "FIRES (ZH only)"
                summary["fires_zh_only"] += 1
            elif en_hit:
                status = "FIRES (EN only)"
                summary["fires_en_only"] += 1
            else:
                status = "**SILENT**"
                summary["silent"] += 1
            focal_label = f"{t.get('artist')} — {t.get('song')}"
            target_label = f"{target.get('artist')} — {target.get('song')}"
            lines.append(
                f"| {focal_pos} | {focal_label} | {tp} | {target_label} | {zh_cell} | {en_cell} | {status} |"
            )

    lines.append("")
    lines.append("## Summary")
    lines.append("")
    total = sum(summary.values())
    for k, v in summary.items():
        lines.append(f"- {k}: {v} ({100 * v / total:.0f}%)")
    lines.append(f"- total candidate-focal pairs: {total}")

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")
    for k, v in summary.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
